services:
    dso_user.update_location_listener:
        class: Dso\UserBundle\EventListener\UpdateLocationSettingsSubscriber
        calls:
            - [setUserManager, ["@fos_user.user_manager"]]
        tags:
            - { name: kernel.event_subscriber }
