services:
    dso_user.update_location_listener:
        class: Dso\UserBundle\EventListener\UpdateLocationSettingsSubscriber
        calls:
            - [setUserManager, ["@fos_user.user_manager"]]
        tags:
            - { name: kernel.event_subscriber }

    dso_app.provider.oauth:
        class: Dso\UserBundle\Security\Core\User\OAuthUserProvider
        arguments: [@fos_user.user_manager, {facebook: facebookID}]
