dso_observations_log_homepage:
    path:     /observations-log/
    defaults: { _controller: DsoObservationsLogBundle:Dashboard:index }
    methods:  [GET]

dso_observations_log_entries_import_external:
    path:     /observations-log/import/
    defaults: { _controller: DsoObservationsLogBundle:Entries:importExternal }
    methods:  [GET, POST]

dso_observations_log_entries_view_logged:
    path:     /observations-log/view-logged/
    defaults: { _controller: DsoObservationsLogBundle:Entries:viewLogged }
    methods:  [GET]

dso_observations_log_log:
    path:     /observations-log/log/
    defaults: { _controller: DsoObservationsLogBundle:Dashboard:log }
    methods:  [GET, POST]

dso_observations_log_log_ajax_user:
    path:     /observations-log/log-ajax-user/
    defaults: { _controller: DsoObservationsLogBundle:Dashboard:logAjax }
    methods:  [GET]

obs_lists:
    resource: "@DsoObservationsLogBundle/Controller/ObsListController.php"
    prefix:   /all
    type:     annotation

logged_objects:
    resource: "@DsoObservationsLogBundle/Controller/LoggedObjectController.php"
    prefix:   /all
    type:     annotation
