services:
    dso_observations_log.skylist_entry:
        class: Dso\ObservationsLogBundle\Services\SkylistEntry
        calls:
            - [setEm, ["@doctrine.orm.entity_manager"]]

    dso_observations_log.diagram_data:
        class: Dso\ObservationsLogBundle\Services\DiagramData
        calls:
            - [setEm, ["@doctrine.orm.entity_manager"]]

    dso_observations_log.logged_stats:
        class: Dso\ObservationsLogBundle\Services\LoggedStats
        calls:
            - [setEm, ["@doctrine.orm.entity_manager"]]

    dso_observations_log.format_dso_name:
        class: Dso\ObservationsLogBundle\Services\FormatDsoName
