dso_planner_homepage:
    pattern:  /planner/
    defaults: { _controller: DsoPlannerBundle:Planner:index }
    methods:  [GET]

dso_planner_predefined_filter:
    pattern:  /planner/filter-predefined/
    defaults: { _controller: DsoPlannerBundle:Planner:filterPredefined }
    methods:  [GET]

dso_planner_custom_filter:
    pattern:  /planner/filter-custom/
    defaults: { _controller: DsoPlannerBundle:Planner:filterCustom }
    methods:  [GET]

dso_planner_feedback:
    pattern:  /feedback/
    defaults: { _controller: DsoPlannerBundle:Feedback:feedback }
    methods:  [GET, POST]

dso_planner_feedback_sent:
    pattern:  /feedback-sent/
    defaults: { _controller: DsoPlannerBundle:Feedback:feedbacksent }
    methods:  [GET]

dso_planner_current_location_settings:
    pattern:  /planner/location_settings
    defaults: { _controller: DsoPlannerBundle:Planner:locationSettings }
    methods:  [GET]

dso_planner_display_location_settings_form:
    pattern:  /planner/location_settings_form
    defaults: { _controller: DsoPlannerBundle:Planner:editlocationSettings }
    methods:  [GET]

dso_planner_update_location_settings:
    pattern:  /planner/location_settings
    defaults: { _controller: DsoPlannerBundle:Planner:updateLocationSettings }
    methods:  [POST]

dso_planner_async_update_settings:
    pattern:  /planner/async/update_settings
    defaults: { _controller: DsoPlannerBundle:Planner:asyncUpdateSettings }
    methods:  [POST]
    options:
        expose: true

dso_planner_async_add_item_to_list:
    pattern:  /planner/observing-list/add-item
    defaults: { _controller: DsoPlannerBundle:Planner:asyncAddItemToLists }
    methods:  [POST]
    options:
        expose: true

dso_planner_async_retrieve_observing_list:
    pattern:  /planner/observing-list/retrieve/{dsoId}/
    defaults: { _controller: DsoPlannerBundle:Planner:asyncRetrievePlannedLists }
    methods:  [GET]
    options:
        expose: true
    requirements:
        dsoId: '\d+'
