dso_planner_homepage:
    pattern:  /planner/
    defaults: { _controller: DsoPlannerBundle:Home:index }

dso_planner_predefined_filter:
    pattern:  /planner/filter/
    defaults: { _controller: DsoPlannerBundle:Home:filterPredefined }
dso_planner_feedback:
    pattern:  /feedback/
    defaults: { _controller: DsoPlannerBundle:Feedback:feedback }
dso_planner_feedback_sent:
    pattern:  /feedback-sent/
    defaults: { _controller: DsoPlannerBundle:Feedback:feedbacksent }
