dso_planner_homepage:
    pattern:  /planner/
    defaults: { _controller: DsoPlannerBundle:Planner:index }

dso_planner_predefined_filter:
    pattern:  /planner/filter-predefined/
    defaults: { _controller: DsoPlannerBundle:Planner:filterPredefined }

dso_planner_custom_filter:
    pattern:  /planner/filter-custom/
    defaults: { _controller: DsoPlannerBundle:Planner:filterCustom }

dso_planner_feedback:
    pattern:  /feedback/
    defaults: { _controller: DsoPlannerBundle:Feedback:feedback }

dso_planner_feedback_sent:
    pattern:  /feedback-sent/
    defaults: { _controller: DsoPlannerBundle:Feedback:feedbacksent }

dso_planner_location_settings:
    pattern:  /planner/location_settings
    defaults: { _controller: DsoPlannerBundle:Planner:locationSettings }
    methods:  [GET]

dso_planner_update_location_settings:
    pattern:  /planner/location_settings
    defaults: { _controller: DsoPlannerBundle:Planner:updateLocationSettings }
    methods:  [POST]
