parameters:
    dso_planner.mysql_service.class: Dso\PlannerBundle\Services\SQL\MySqlService
    dso_planner.visible_objects.class: Dso\PlannerBundle\Services\CreateVisibleObjectsTable
    dso_planner.filter_results.class: Dso\PlannerBundle\Services\FilterResults

services:
    dso_planner.mysql_service:
        class: %dso_planner.mysql_service.class%
        arguments: [@database_connection]
    dso_planner.visible_objects:
        class: %dso_planner.visible_objects.class%
        arguments: [@dso_planner.mysql_service]
    dso_planner.filter_results:
        class: %dso_planner.filter_results.class%
        arguments: [@dso_planner.mysql_service]