parameters:
    dso_planner.mysql_service.class: Dso\PlannerBundle\Services\SQL\MySqlService
    dso_planner.visible_objects.class: Dso\PlannerBundle\Services\CreateVisibleObjectsTable
    dso_planner.filter_results.class: Dso\PlannerBundle\Services\FilterResults
    dso_planner.settings_manager.class: Dso\PlannerBundle\Services\SettingsManager
    dso_planner.paginate_subscriber.class: Dso\PlannerBundle\Subscriber\PaginateDsosSubscriber
    dso_planner.drop_table_subscriber.class: Dso\PlannerBundle\Subscriber\DropTableSubscriber

services:
    dso_planner.mysql_service:
        class: %dso_planner.mysql_service.class%
        arguments: [@database_connection]
    dso_planner.visible_objects:
        class: %dso_planner.visible_objects.class%
        arguments: [@dso_planner.mysql_service]
    dso_planner.filter_results:
        class: %dso_planner.filter_results.class%
        arguments: [@dso_planner.mysql_service, @knp_paginator]
        calls:
            - [setResultsPerPage, [%planner_results_per_page%]]
    dso_planner.paginate_subscriber:
        class: %dso_planner.paginate_subscriber.class%
        tags:
            - { name: knp_paginator.subscriber }
    dso_planner.drop_table_subscriber:
        class: %dso_planner.drop_table_subscriber.class%
        calls:
            - [setDbConnection, ["@doctrine.dbal.default_connection"]]
        tags:
            - { name: kernel.event_subscriber }
    dso_planner.settings_manager:
        class: %dso_planner.settings_manager.class%
        calls:
            - [setVisibleObjectsService, ["@dso_planner.visible_objects"]]
            - [setDispatcher, ["@event_dispatcher"]]
            - [setEm, ["@doctrine.orm.entity_manager"]]
