dso_observations_log:
    resource: "@DsoObservationsLogBundle/Resources/config/routing.yml"
    prefix:   /

dso_user:
    resource: "@DsoUserBundle/Resources/config/routing.yml"
    prefix:   /

dso_home:
    resource: "@DsoHomeBundle/Resources/config/routing.yml"
    prefix:   /

dso_planner:
    resource: "@DsoPlannerBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /auth
