security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: /auth/login
                check_path: /auth/login_check
                always_use_default_target_path: false
                default_target_path: /planner
            logout:
                path:   /auth/logout
                target: /auth/login
            anonymous:    true
            methods: [GET, POST, PUT, DELETE]

    access_control:
        - { path: ^/auth/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/auth/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/planner/, role: ROLE_USER }
        - { path: ^/observations-log/, role: ROLE_USER }
        - { path: ^/user-admin/, role: ROLE_ADMIN } #for the future user management