dso_home_homepage:
    pattern:  /
    defaults: { _controller: DsoHomeBundle:Home:index }
    methods:  [GET]

dso_home_terms_and_conditions:
    pattern:  /terms-and-conditions
    defaults: { _controller: DsoHomeBundle:Home:termsAndConditions }
    methods:  [GET]

dso_check_facebook:
    pattern:  /login/check-facebook
    defaults: { _controller: DsoHomeBundle:Home:checkFacebook }
    methods:  [GET]

dso_search_form:
    pattern:  /search
    defaults: { _controller: DsoHomeBundle:Home:search }
    methods:  [POST]

dso_home_feedback:
    pattern:  /feedback/
    defaults: { _controller: DsoHomeBundle:Feedback:feedback }
    methods:  [GET, POST]

dso_home_feedback_sent:
    pattern:  /feedback-sent/
    defaults: { _controller: DsoHomeBundle:Feedback:feedbacksent }
    methods:  [GET]
