services:
    kernel.listener.dso_exception_listener:
        class: Dso\HomeBundle\EventListener\DsoExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
        calls:
            - [setMailer, [@mailer]]
            - [setTemplateService, [@templating]]
            - [setAdminEmail, [%administrator_email%]]

    dso_name_format.twig_extension:
        class: Dso\HomeBundle\Twig\DsoNameExtension
        calls:
            - [setFormatter, [@dso_observations_log.format_dso_name]]
        tags:
            - { name: twig.extension }
