parameters:
#    dso_home.example.class: Dso\HomeBundle\Example

services:
#    dso_home.example:
#        class: %dso_home.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
